# Generated by Django 4.0.3 on 2022-04-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RuralPro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testnews',
            name='createTime',
        ),
        migrations.RemoveField(
            model_name='testnews',
            name='digest',
        ),
        migrations.RemoveField(
            model_name='testnews',
            name='editor',
        ),
    ]
