# Generated by Django 4.0.3 on 2022-04-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuralPro', '0002_remove_testnews_createtime_remove_testnews_digest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScrapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test_scrapy',
            },
        ),
    ]
